#!/bin/bash

apt-get update
apt-get -y --force-yes install postgresql-client
apt-get -y --force-yes install vim
apt-get -y --force-yes install curl
apt-get -y --force-yes install sudo
apt-get -y --force-yes install inotify-tools
apt-get -y --force-yes install rebar

mix local.hex --force
mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
apt-get -y --force-yes install nodejs
apt-get -y --force-yes install build-essential

cd /socialbenchmark/socialbenchmark/ && mix hex.info && mix deps.get
cd /socialbenchmark/socialbenchmark_webapp/ && mix deps.get && npm install
