#!/bin/bash

apt-get update
apt-get -y install build-essential
apt-get -y install git
apt-get -y install vim
apt-get -y install cpanminus
apt-get -y install wget
apt-get -y install sudo
apt-get -y install lsb-release
apt-get -y install curl

# PostgreSQL 12 repo
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list

# Node
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

apt-get update
apt-get -y install postgresql-12 postgresql-client-12 postgresql-server-dev-12
apt-get -y install nodejs



# TODO: change /etc/postgresql/12/main/pg_hba.conf
/etc/init.d/postgresql start

git clone https://github.com/krychu/quake-stats.git
cpanm Mojolicious
cpanm DBD::Pg
cpanm Array::Split
cpanm Log::Any
cpanm Syntax::Keyword::Try
cpanm JSON::Parse

cd /quake-stats/scripts && ./create_db.pl
cd /quake-stats/scripts && ./pg_load_schema_file.sh
# TODO: get sampledata
cd /quake-stats/scripts && ./import_sample_data.pl
cd /quake-stats/web && npm install



cd /quake-stats/web && npx webpack
cd /quake-stats/web && morbo app.pl